services:
  api:
    image: zccajgb/simplicity-api:latest
    build:
      context: ./api
    ports:
      - "9001:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017

  client:
    image: zccajgb/simplicity-client:latest
    build:
      context: ./client
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

  cron:
    image: zccajgb/simplicity-cron:latest
    build:
      context: ./cron
