services:
  api:
    image: zccajgb/simplicity-api:latest
    build:
      context: ./api
    ports:
      - "9001:8000"
    environment:
      RUST_LOG: info
      ROCKET_LOG_LEVEL: normal
      MONGO_URL: ${MONGO_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      API_URI: ${API_URI}
      API_KEY: ${API_KEY}
      PROD: true
      REDIRECT_URL: https://simplicity.buckleyresearch.com

  client:
    image: zccajgb/simplicity-client:latest
    build:
      context: ./client
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    environment:
      API_URI: something

  cron:
    image: zccajgb/simplicity-cron:latest
    build:
      context: ./cron
