FROM rust:latest as builder

ENV ROCKET_ADDRESS=0.0.0.0
ENV ROCKET_PORT=8000

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release

COPY . .
RUN cargo install cargo-watch
EXPOSE 8000

CMD ["cargo", "watch", "-q", "-w", "src", "-x", "run"]
